# Generated by Django 3.0.5 on 2020-04-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
