# Generated by Django 3.0.5 on 2020-04-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200401_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='name',
        ),
    ]
