# Generated by Django 3.0.5 on 2020-04-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_upload_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
