# Generated by Django 3.0.5 on 2020-04-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200401_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
